name: build
run-name: Build triggered by ${{ github.actor }}
on: [push]
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Run reaper_usdocml
        id: run_reaper_usdocml
        run: python -m reaper_usdocml example/Reaper_Api_Documentation.USDocML reaper.d.ts -r example/replacements.json 2>&1 | tee build.log
      - name: Generate release description
        run: |
          echo "Build output:" > release.md
          echo "" >> release.md
          echo "\`\`\`" >> release.md
          cat build.log >> release.md
          echo "\`\`\`" >> release.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release.md
          files: reaper.d.ts
        if: startsWith(github.ref, 'refs/tags/')
